### ISSUE TITLE
Unhelpful error when user doesn't have Kerberos ticket

### ISSUE THREAD

**Issue by SeanDS** [duncanmmacleod/ciecplib#3]
When I call `request([url], use_kerberos=True)` without first having obtained a Kerberos ticket, the error message is:

```
/path/to/ecp.py in generate_request_header(self, req, headers)
    100             return None
    101 
--> 102         if kerberos.authGSSClientStep(self.context, neg_value) < 0:
    103             return None
    104         return 'Negotiate %s' % kerberos.authGSSClientResponse(self.context)

GSSError: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('No Kerberos credentials available', -1765328243))
```

I think it'd be better to deal with this error internally and issue a message to the user about running `kinit` first.

**Comment by duncanmmacleod** [comment]
@SeanDS, the error messsage does actually tell you exactly what the problem is, namely

> No Kerberos credentials available

However, I agree that its a bit lost amongst the other messages and error codes printed. It is relatively easy to pull out that single error message so that the traceback presents as:

```
Traceback (most recent call last):
...
  File "/Users/duncan/Library/Python/2.7/lib/python/site-packages/ligo/org/ecp.py", line 103, in generate_request_header
    if kerberos.authGSSClientStep(self.context, neg_value) < 0:
kerberos.GSSError: No Kerberos credentials available (default cache: KCM:)
```

Would that be sufficient, in your opinion? I'm hesitant to start appending other messages about kinit, primarily because I have no idea how many different kerberos error problems might present, and searching for strings in messages complicates the code unnecessarily (IMHO).

**Comment by SeanDS** [comment]
Hmm, tricky. I guess that this will be one of the most common errors people run into when using the library, so it should have a clear error message. On the other hand, as you say, it involves code complication.

It looks like there's a "minor" error code supplied alongside the text, so it might be straightforward to search for that and then throw a (e.g.) `NoKerberosTicketException`.
